### PR TITLE
added more code to do better(auto publish linux version with demo code)

### PR DESCRIPTION
**Pull request by 2439905184**
1.add windows.yml to auto build exe for windows x64
2.added more code to linux.yml to auto build suika2 with your demo code (pack engine with your demo script together)
image
at the end ,thanks to this man's actions.
[copy-action](https://github.com/canastro/copy-action)
This helped me l lot.
I spend some time try to resolve the "cp" command problem on action's linux machine.

### CODE REVIEW

**Comment by ktabata** [comment]
Thank you for the PR.

> 1.add windows.yml to auto build exe for windows x64

In `build/mingw` directory, we build x86 32bit binary.
For 64bit binary, use `build/mingw64`.

We don’t use `libasound2-dev`, `libx11-dev` and `libxpm-dev` for Windows target.

There is a typo to be fixed: sukka -> suika

Question: Where do the actions store the binary files? This is my first time to use action, so I'm curious.

**Comment by 2439905184** [comment]
Hi ktabata,just follow the image I show you below
image
image
image
image
If you click here,you can see the actions runs(console output)
image
this page shows every thing happens in building time

**Comment by 2439905184** [comment]
https://github.com/benikabocha/saba/commit/d9870991f31a207f949743c38820f629eed89ba6
you can see here.
image
there are some code about enviroment var (变数 in Japanese)（变量in Chinese）
So this job will use clang compiler to compile saba.
So there must have a way to compile suika2 to x86.(Maybe add some config codes in makefile?)
https://github.com/marketplace/actions/run-on-architecture
Maybe you can try this action,but I haven't tried.(It seems that action will not run on x86,x64 arch.
You can find other's actions at here https://github.com/marketplace

**Comment by 2439905184** [comment]
gcc -m32 -O3 index.c -o index   //this is to compile to x86
I find a cmd code ,"-m32" is a parameter to used by gcc

**Comment by ktabata** [comment]
Hi 2439905184,
Thank you for the detailed explanation about artifacts.
Now, I understand.

BTW, we use `i686-w64-mingw32-gcc` for 32bit Windows target.
It compiles C programs to 32bit code without `-m32` option.
Just call `make` to use it.

**Comment by 2439905184** [comment]
Hi katabata, I have wrote the windows.yml file,so you can change parameter by yourself  in order to compile with mingw32-gcc for windows.

**Comment by ktabata** [comment]
Ok, then I'll accept the PR and fix it just a little.

**Pull request merged**
