### PR TITLE
translated tutorail.md to Chinese

### PR DESCRIPTION
**Pull request by 2439905184**
translate commit is cfc95e2e2b00bd3e0ec33e993591f312a34bf59e

### CODE REVIEW

**Comment by ktabata** [comment]
Thank you!
The section "启用英文模式" was removed from English tutorial.md because `language=English` is initially enabled in English distribution file.
Do you want to leave it?

**Comment by 2439905184** [comment]
No,I don't want to leave this in tutorail.zh.md.
Because for Chinese users ,they may not need this

**Comment by ktabata** [comment]
Ok, please remove the section, then push it to your branch.

**Comment by 2439905184** [comment]
> Ok, please remove the section, then push it to your branch.

removed

**Pull request merged**
